### ISSUE TITLE
Hot to fail expression parser if no operator in input

### ISSUE THREAD

**Issue by zim32** [parsica-php/parsica#54]
I have simple math expression defined like this 

```
$arithmeticExpression->recurse(expression(
    $parens($arithmeticExpression)->or($token($term)),
    [
        leftAssoc(
            binaryOperator($token(string("-")), fn($l, $r) => new MinusOperator($l, $r))
        ),
        leftAssoc(
            binaryOperator($token(string("+")), fn($l, $r) => new PlusOperator($l, $r))
        ),
    ]
));
```

But this parser succeeds when only term provided. F.e. it parses inputs like
123 + 321
and just
123

Hot to prevent it succeed parsing without any operator?

**Comment by turanct** [comment]
The `expression` parser assumes you're parsing an expression language, where every expression is something that can be evaluated to a value. This means that a value itself (a "term" of the expression) is also a valid expression.

```
1 + (2 * 3)
```

is an expression that's made up of a few expressions. One of those expressions is `1`, which is a single term. If you would create a simple AST out of this, using an expression parser following basic math's rules, we would get something like this:

```
[
    "+",
    [ "1" ],
    [
        "*",
        [ "2" ],
        [ "3" ],
    ],
]
```

As you can see, if `1` or `2` or `3` (the terms) are not valid expressions by themselves, it becomes impossible to use this `expression()` parser to parse this language.

So I think your problem is by design.

However, if you just want to parse simple expressions like this, it should be possible to write your own using parsica.

**Comment by zim32** [comment]
Thanks
